//
// Generated file, do not edit! Created by opp_msgtool 6.0 from mecrt/packets/apps/DistPV.msg.
//

#ifndef __DISTPV_M_H
#define __DISTPV_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class DistPV;
#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk

/**
 * Class generated from <tt>mecrt/packets/apps/DistPV.msg:20</tt> by opp_msgtool.
 * <pre>
 * class DistPV extends inet::FieldsChunk
 * {
 *     unsigned int appId; // the application id of the vehicle, 4 bytes
 *     unsigned short preferenceValue;	// the preference value of the application for scheduling, 2 bytes
 * 
 *     chunkLength = inet::B(6);
 * }
 * </pre>
 */
class DistPV : public ::inet::FieldsChunk
{
  protected:
    unsigned int appId = 0;
    unsigned short preferenceValue = 0;

  private:
    void copy(const DistPV& other);

  protected:
    bool operator==(const DistPV&) = delete;

  public:
    DistPV();
    DistPV(const DistPV& other);
    virtual ~DistPV();
    DistPV& operator=(const DistPV& other);
    virtual DistPV *dup() const override {return new DistPV(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual unsigned int getAppId() const;
    virtual void setAppId(unsigned int appId);

    virtual unsigned short getPreferenceValue() const;
    virtual void setPreferenceValue(unsigned short preferenceValue);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const DistPV& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, DistPV& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline DistPV *fromAnyPtr(any_ptr ptr) { return check_and_cast<DistPV*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __DISTPV_M_H

