//
// Generated file, do not edit! Created by opp_msgtool 6.0 from mecrt/packets/apps/DistToken.msg.
//

#ifndef __DISTTOKEN_M_H
#define __DISTTOKEN_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class DistToken;
#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk

/**
 * Class generated from <tt>mecrt/packets/apps/DistToken.msg:20</tt> by opp_msgtool.
 * <pre>
 * class DistToken extends inet::FieldsChunk
 * {
 *     unsigned int appId; // the application id of the vehicle, 4 bytes
 *     double utilReduction;   // the accumulated utility reduction of the application, 8 bytes
 *     string targetCategory;	// the category of candidates to select, 4 bytes
 *     unsigned short preferenceValue;	// the preference value of the application for scheduling, 2 bytes
 *     bool isScheduled;		// whether the application has been scheduled, 1 byte
 * 
 *     chunkLength = inet::B(19);
 * }
 * </pre>
 */
class DistToken : public ::inet::FieldsChunk
{
  protected:
    unsigned int appId = 0;
    double utilReduction = 0;
    omnetpp::opp_string targetCategory;
    unsigned short preferenceValue = 0;
    bool isScheduled_ = false;

  private:
    void copy(const DistToken& other);

  protected:
    bool operator==(const DistToken&) = delete;

  public:
    DistToken();
    DistToken(const DistToken& other);
    virtual ~DistToken();
    DistToken& operator=(const DistToken& other);
    virtual DistToken *dup() const override {return new DistToken(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual unsigned int getAppId() const;
    virtual void setAppId(unsigned int appId);

    virtual double getUtilReduction() const;
    virtual void setUtilReduction(double utilReduction);

    virtual const char * getTargetCategory() const;
    virtual void setTargetCategory(const char * targetCategory);

    virtual unsigned short getPreferenceValue() const;
    virtual void setPreferenceValue(unsigned short preferenceValue);

    virtual bool isScheduled() const;
    virtual void setIsScheduled(bool isScheduled);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const DistToken& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, DistToken& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline DistToken *fromAnyPtr(any_ptr ptr) { return check_and_cast<DistToken*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __DISTTOKEN_M_H

