//
// Generated file, do not edit! Created by opp_msgtool 6.0 from mecrt/packets/routing/OspfHello.msg.
//

#ifndef __OSPFHELLO_M_H
#define __OSPFHELLO_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class OspfHello;
#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk

/**
 * Class generated from <tt>mecrt/packets/routing/OspfHello.msg:19</tt> by opp_msgtool.
 * <pre>
 * class OspfHello extends inet::FieldsChunk
 * {
 *     uint32 senderIp;
 *     uint32 neighborIp;
 * 
 *     chunkLength = inet::B(8);
 * }
 * </pre>
 */
class OspfHello : public ::inet::FieldsChunk
{
  protected:
    uint32_t senderIp = 0;
    uint32_t neighborIp = 0;

  private:
    void copy(const OspfHello& other);

  protected:
    bool operator==(const OspfHello&) = delete;

  public:
    OspfHello();
    OspfHello(const OspfHello& other);
    virtual ~OspfHello();
    OspfHello& operator=(const OspfHello& other);
    virtual OspfHello *dup() const override {return new OspfHello(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual uint32_t getSenderIp() const;
    virtual void setSenderIp(uint32_t senderIp);

    virtual uint32_t getNeighborIp() const;
    virtual void setNeighborIp(uint32_t neighborIp);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const OspfHello& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, OspfHello& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline OspfHello *fromAnyPtr(any_ptr ptr) { return check_and_cast<OspfHello*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __OSPFHELLO_M_H

